### ISSUE TITLE
Every Actual read job crashes: "query.serialize is not a function" (regression in #371)

### ISSUE THREAD

**Issue by nrosier** [nrosier/Balancr#381]
Seen on `2.0.0-rc.1`, immediately after upgrading from `1.2.3`. The banner shows:

> A background job last failed, so these figures may be out of date.
>
> - Net worth — query.serialize is not a function
> - Signals — query.serialize is not a function
> - Budget sync — query.serialize is not a function

## Root cause

`#371` split the Actual client into a per-tenant forked worker process (`src/adapters/actual/client.ts`, `worker.ts`), routing every `actual.*` call over IPC. Before that split, `runAql` in `src/adapters/actual/queries.ts` called `actual.aqlQuery(build(actual.q))` with a **live** `Query` object, all in one process — `@actual-app/api`'s `aqlQuery(query)` calls `query.serialize()` internally, which worked because `query` really was a `Query` instance.

`runAql` now (`src/adapters/actual/queries.ts:48-69`) tries to work around IPC by calling `.serialize()` itself before crossing the process boundary:

```ts
const state = build().serialize()
const raw = await withActual(db, tenantId, (actual) =>
  actual.aqlQuery(state as unknown as Query),
)
```

The comment above it claims "`aqlQuery` itself accepts either a live `Query` or its serialized state — the worker gets the latter," but that's not true of the installed `@actual-app/api` (`node_modules/@actual-app/api/dist/index.js`, `aqlQuery(query)`): it unconditionally calls `query.serialize()` again, with no `instanceof Query` check (unlike the internal `aqlQuery$1`, which does check). So the worker process ends up calling `.serialize()` on an already-plain object that has no such method, throwing `query.serialize is not a function`.

Every job that reads from Actual via `runAql` hits this — `src/jobs/networth.ts`, `src/jobs/signals.ts`, `src/jobs/sync.ts` — which is effectively every Actual read path, all at once.

## Fix direction

`state` is plain data and can safely cross IPC; the missing piece is a `.serialize()` method for `@actual-app/api`'s `aqlQuery` to call, which has to be reattached *inside the worker process* (functions can't cross IPC either). Likely fix: special-case `aqlQuery` in `worker.ts`'s `runCall` to wrap its single arg as `{ serialize: () => arg }` before forwarding to `api.aqlQuery`, rather than relying on the plain state satisfying the real `Query` interface.

## Impact

Net worth, signals and the Actual budget sync jobs fail on every run on `2.0.0-rc.1`. This blocks `2.0.0` — filed against the multi-tenant milestone since it's a regression from #371, found during rc testing.

**Comment by nrosier** [comment]
Fixed in fc7c5c5, verified with a direct-IPC test against a real Dockerized Actual server, and shipped in v2.0.0-rc.2.
